---
title: "discussion"
author: "Jorrit"
date: "2024-04-14"
output: pdf_document
---
The results shown above demonstrate the concentrations produced as a result of the processes occurring in the aquifer as water travels down through the soil. While these processes may seem as separate entities, they are, in fact, interlinked with one another. The model produced makes use of the dependencies of these rates and the corresponding concentrations produced as a result. The coupling of the processes allows for an added level of complexity as well as a greater understanding of the processes themselves. It demonstrates how each of the processes is dependent upon the others as they will have an impact on the concentrations of the pollutants as well as the distribution of the concentrations and processes in the aquifer.

The well is located at a distance of 200 meters from the riverbank. This distance is shown to be a good position for the pumping well as the water quality is safe, and when the well is situated closer to the river, the water quality is not high enough for safe human consumption. This is due to the fact that the distance is less than what is required to remove enough of the Ammonia from the water. The Ammonia concentration is the main cause of concern regarding water quality, as the concentrations remain high between 20 and 200 meters. Following this, the concentration of Dissolved Organic Nitrogen is particularly high until it reaches a distance of 40 meters from the edge of the river. The Nitrate and Oxygen concentrations do not exceed the threshold of a dangerous concentration. The aerobic mineralisation of the dissolved Organic Nitrogen contributes to the increase in the Ammonia concentration. Due to this high concentration, it takes the process of nitrification much longer, which therefore requires a much longer distance to reduce the ammonia into a reduced form, in this case, nitrate. The increased distance required for the ammonia concentration to drop to a safe concentration will cause the location of the well to be further away from the aquifer in order to produce water with good quality.

For Dissolved Organic Nitrogen to be broken down into a consumable element for bacteria, the dissolved organic nitrogen needs to go through the process of aerobic mineralisation. During this process, the dissolved organic nitrogen will be broken down into ammonia. While the amount of ammonia produced in this step is of concern given how far it forces the extraction well to move from the edge of the river, there are also benefits. Were the aerobic mineralisation rate to be increased, there would be an increase in the amount of ammonia produced. It would, however, reduce the concentration of the dissolved organic nitrogen much quicker. However, this would in turn cause a greater strain upon the nitrification process as the ammonia would need a much farther distance to travel before it could be considered safe to drink.

As ammonia has the highest concentration of all the pollutants moving through the aquifer, it is of more concern than the others. The easiest way to help remove as much of the ammonia in as short a space of time is to increase the nitrification rate. However, this comes with its own number of setbacks. Nitrification is an aerobic process within the nitrogen cycle, and in order to increase the rate of nitrification, there would be an increased demand on the amount of oxygen present in the ground. This creates the problem of a reduction in oxygen concentration in the soil. Should the oxygen concentration in the soil be increased, however, this would require a continued addition of oxygen as it is consumed through the process of nitrification. Steps such as these, while they would reduce the concentration of ammonia and the distance the well is required to be located out, may prove to be too costly.

The levels of nitrate present in the aquifer are not of major concern as even at their highest level, they exist below what is considered a safe threshold. It is, however, important to ensure that these levels do not rise and as much of the nitrate from the pollutants is removed. The process removing the nitrate is denitrification, which is the anaerobic process involved in the nitrogen cycle. At this point, oxygen is no longer available, and this final step involved the nitrate reducing further to Nitrogen gas. As the increase in denitrification would require the concentration of nitrate to be higher, it would also need the oxygen concentration to be reduced faster. This would have a negative effect upon the breakdown of ammonia to nitrate, increasing the distance required to ensure that the water is at a safe quality.
