---
title: "introduction"
author: "Willem Poelman, Denis Power and Jorrit Bakker"
date: "2024-04-01"
output: pdf_document
---

The purpose of this report is to demonstrate the movement, via advection, of nutrients from a polluted river source through an aquifer. In addition, it will demonstrate the chemical reactions that occur as the pollutant travels through the aquifer, differentiating the different compounds which are formed.

The model will make use of the derived differential equations used for stoichiometry and the reaction rates which were deemed appropriate given the constituent parts in the system.

Within the model, different chemical processes are added to show their interconnection and dependence upon concentrations produced through reactions within the aquifer and the transport of compound concentrations from outside (the river). These processes are primarily aeration, nitrification, denitrification, and aerobic mineralization. Aeration of the soil affects aerobic mineralization, which in turn affects the dissolved organic nitrogen; this process reduces the DON to a consumable form of nitrogen, in the form of Ammonia [@Doussan1997]. Nitrification is the reduction of ammonia to another nitrogen-based product, in this case, Nitrate [@Soetaert1996]. Once the oxygen concentration within the aquifer has been lowered by the nitrification process, denitrification can take place [@Spiteri2008]. This process involves making use of the ammonia which has been produced in the nitrification process and finishes its reduction to nitrogen gas.

The overall process described by this model is bank filtration used for the cleaning of surface water to a grade suitable for human use. The use of bank filtration is of particular importance as for many counties it is used for the pre-treatment or treatment of water before human use [@Hiscock2002]. Bank infiltration makes use of the naturally occurring processes present in the banks of rivers, namely; aeration, aerobic mineralization, nitrification, and denitrification. These processes allow for the removal of DON. The layers of sand and silt at the bed of a river act as a filter system through which nutrients and pathogens may be removed [@Tufenkji2002]. The system presented is a simplified version of the naturally occurring riverbanks where the distance from the source and rate-limiting elements, such as oxygen, play an important role not only in the chemical processes occurring but also in where these chemical processes occur [@Tufenkji2002].

The consequences of this distance-related limitation on the processes will be demonstrated within the model. As this is a simplified model, in a real scenario the ratio of nitrogen and phosphorus in the system would be greater than the Redfield ratio of 16:1. These effects are the result of anthropogenic discharges via farming and industry.
